ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks
        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ""
    autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
    autoupdate_schedule: weekly
    skip: []
    submodules: false
exclude: "^model-output/.*\\.(csv|parquet)$|^model-metadata/.*\\.ya?ml$"
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
        args: ["--allow-multiple-documents"]
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: ["--autofix", "--no-sort-keys"]
    -   id: trailing-whitespace
-   repo: https://github.com/crate-ci/typos
    rev: v1
    hooks:
    -   id: typos
        args: ["--force-exclude"]
