[default]
extend-ignore-identifiers-re = [
    "AttributeID.*Supress.*",
]

[default.extend-identifiers]
AttributeIDSupressMenu = "AttributeIDSupressMenu"

[default.extend-words]
# words that should not be corrected
Damon = "Damon"
dot_acn = ".acn"
ba = "ba"
ned = "Ned"
ND = "ND"
arange = "arange"
Aer = "Aer"
O957 = "O957"
gam = "gam"
boun = "boun"
thq = "thq"
clien = "clien"
AKS = "AKS"
HSA = "HSA"
RTO = "RTO"
Winn = "Winn"
OT = "OT"

[files]
extend-exclude = [
    ".gitignore",
    ".pre-commit-config.yaml",
    ".github/ISSUE_TEMPLATE/",
    "*.bib",
    "*.html",
    "*.js",
    "*.csl",
    "*.css",
    "*.ipynb",
    "*.csv"
]
