on:
  pull_request:
    types:
      - synchronize
      - opened
      - edited
  check_suite:
    types:
      - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge,data-submission,!other-files-updated,!documentation,!code"
