name: "CovidHub-ensemble"
on:
  workflow_dispatch:
  schedule:
    - cron: "00 15 * * 4"

jobs:
  generate-covidhub-ensemble:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        install-r: false
        use-public-rspm: true
      
    - name: Install dependencies
      run: |
        install.packages(c("hubEnsemble", "dplyr", "lubridate", "purrr", "hubData", "yaml"))
      shell: Rscript {0}
  
    - name: generate ensemble
      run:  Rscript src/code/get_ensemble.r

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with: 
        message: "Add CovidHub ensemble forecasts"
        default_author: github_actions
        push: true
        new_branch: auto-ensemble

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "Add forecast ensemble"
        title: "Add ensemble forecasts"
        body: "This PR adds ensemble forecasts to the repo."
        branch: "auto-ensemble" 
        base: "main"
        labels: "automerge"