name: "Send a dispatch to internal covidhub-reports"

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - 'target-data/*'
      - 'model-output/CovidHub-ensemble/*'
    
jobs:
  update-webpage-data:
    if: ${{ github.repository_owner == 'CDCgov' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Generate Installation Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.ENT_GH_APP_ID }}
          private-key: ${{ secrets.ENT_GH_APP_KEY }}
          owner: cdcent  
          repositories: covidhub-internal-reports  

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: cdcent/covidhub-internal-reports
          event-type: data-update