name: Send a dispatch to covidhub-reports

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - 'model-output/CovidHub-ensemble/*'
    
jobs:
  update-visualization-data:
    if: ${{ github.repository_owner == 'CDCgov' }}
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ vars.GH_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_KEY }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          repository: CDCgov/covidhub-reports
          event-type: ensemble-added