name: Update oracle output

on:
  workflow_dispatch:
  push:
    branches: 
      - "main"
    paths:
      - "target-data/time-series*"
    
jobs:
  generate-oracle-data:
    if: ${{ github.repository_owner == 'CDCgov' }}
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Generate Installation Token
      id: get_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ vars.GH_APP_ID }}
        private-key: ${{ secrets.GH_APP_KEY }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        install-r: false
        use-public-rspm: true
        extra-repositories: "https://hubverse-org.r-universe.dev"

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        pak-version: "devel"
        packages: |
          any::argparser
          any::tidyr
          any::hubData
          any::hubUtils
          github::cdcgov/forecasttools
  
    - name: Update oracle output from timeseries data
      run: |
        Rscript src/generate_oracle_output.R --base-hub-path '.'

    - name: Check for Changes
      run: |
        git diff --exit-code target-data/oracle-output.parquet || echo "changed=true" >> $GITHUB_ENV 

    - name: Commit changes
      if: env.changed == 'true'
      uses: EndBug/add-and-commit@v9
      with: 
        message: "Update oracle output"
        default_author: github_actions
        push: true
        new_branch: update-oracle-output
  
    - name: Create pull request
      if: env.changed == 'true'
      run: |
        gh pr create --base main --head update-oracle-output --title "Update oracle output" --body "This PR updates the oracle output file given a detected change to the target data time-series file."
      env:
        GH_TOKEN: ${{ steps.get_token.outputs.token }}
