name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
        r-version: "4.5.0"
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/R/renv
        key: r-precommit-cache|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: pre-commit/action@v3.0.1