name: "Hub Submission Validation (R)"

on:
  workflow_dispatch:
  pull_request:
    branches: main
    paths:
      - 'model-output/**'
      - 'model-metadata/*'
      - '!**README**'

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-submission:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7

      - uses: step-security/changed-files@v47
        id: get_changed_files_in_model_output
        with:
          path: model-output
          dir_names: "true"

      - name: "Check output dirs modified"
        shell: bash
        run: |
          if [ "${{ steps.get_changed_files_in_model_output.outputs.all_modified_files }}" = "CovidHub-ensemble" ]; then
            echo "skip_submit_window_check=true" >> "$GITHUB_ENV"
          else
            echo "skip_submit_window_check=false" >> "$GITHUB_ENV"
          fi

      - uses: hubverse-org/hubverse-actions/validate-submission@main
        with:
          skip_submit_window_check: ${{ env.skip_submit_window_check }}
