name: "Hub Submission Validation (R)"

on:
  workflow_dispatch:
  pull_request:
    branches: main

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-submission:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v7

      - name: "Get model output directory changes"
        id: "model_output_diffs"
        uses: step-security/changed-files@v47
        with:
          path: model-output
          dir_names: "true"

      # point at fork until install R option merged to main or rejected
      - uses: dylanhmorris/hubverse-actions/validate-submission@9a6fa991f6ff350cd5c51737532fc36cc3dbe23d
        with:
          install_r: true
          skip_submit_window_check: ${{ steps.model_output_diffs.outputs.all_modified_files == 'CovidHub-ensemble' }}
