name: Hub Submission Validation (R)

on:
  workflow_dispatch:
  pull_request:
    branches: main

jobs:
  validate-submission:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
          use-public-rspm: true
          extra-repositories: 'https://hubverse-org.r-universe.dev'

      - name: Update R
        run: |
          sudo apt-get update

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::hubValidations
            any::sessioninfo

      - name: Get changed files
        id: get_changed_files_in_model_output
        uses: tj-actions/changed-files@v45
        with:
          path: 'model-output'
          dir_names: 'True'
      
      - name: check if ensemble
        run: |   
          if echo "${{ steps.get_changed_files_in_model_output.outputs.all_modified_files }}" | grep -q "CovidHub-ensemble"; then
            { echo "model=ensemble" | tee -a $GITHUB_ENV; }
          else
            { echo "model=other" | tee -a $GITHUB_ENV; }
          fi

      - name: Run validations
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          library("hubValidations")
          library("hubUtils")
          tasks <- hubUtils::read_config(".", "tasks")
          rounds <- hubUtils::get_round_ids("tasks")
          current <- rounds[which.min(abs(Sys.Date() - as.Date(rounds)))]
          slug <- "CovidHub-ensemble"
          ensemble <- file.path("model-output", slug,
            paste0(current, "-", slug, ".csv"))
          v <- hubValidations::validate_pr(
              gh_repo = Sys.getenv("GITHUB_REPOSITORY"),
              pr_number = Sys.getenv("PR_NUMBER"),
              skip_submit_window_check = file.exists(ensemble)
          )
          hubValidations::check_for_errors(v, verbose = TRUE)
        shell: Rscript {0}
